name: dating_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  image_picker: ^1.1.0
  file:
  dots_indicator: ^3.0.0
  connectivity_plus:
  shared_preferences:
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  country_pickers_v2: ^3.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.1
  pin_input_biometric_authenticator: ^0.0.4
  intl: ^0.19.0
  colorful_safe_area: ^1.0.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - lib/presentation/home_page/models/

  fonts: 
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
    - family: SF Pro Text
      fonts: 
        - asset: assets/fonts/SFProTextSemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansRegular.ttf
          weight: 400
    - family: Rubik
      fonts: 
        - asset: assets/fonts/RubikMedium.ttf
          weight: 500
        - asset: assets/fonts/RubikRegular.ttf
          weight: 400
