import 'controller/verification_one_controller.dart';import 'package:dating_app/core/app_export.dart';import 'package:dating_app/widgets/app_bar/appbar_image.dart';import 'package:dating_app/widgets/app_bar/appbar_title.dart';import 'package:dating_app/widgets/app_bar/custom_app_bar.dart';import 'package:dating_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:flutter/services.dart';import 'package:pin_code_fields/pin_code_fields.dart';class VerificationOneScreen extends GetWidget<VerificationOneController> {const VerificationOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, backgroundColor: appTheme.whiteA700, appBar: CustomAppBar(height: getVerticalSize(79), leadingWidth: 42, leading: AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 18, top: 29, bottom: 26), onTap: () {onTapArrowleft2();}), centerTitle: true, title: AppbarTitle(text: "lbl_verification".tr), styleType: Style.bgOutline), body: Container(width: double.maxFinite, padding: getPadding(left: 16, top: 12, right: 16, bottom: 12), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: getHorizontalSize(311), margin: getMargin(left: 40, right: 43), child: Text("msg_please_provide_the".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 27), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_code_sent_to".tr, style: theme.textTheme.bodyLarge), TextSpan(text: "msg_ronaldrichards_gmail_com".tr, style: CustomTextStyles.titleMediumBlack900SemiBold)]), textAlign: TextAlign.left)), Padding(padding: getPadding(top: 25), child: Obx(() => PinCodeTextField(appContext: context, controller: controller.otpController.value, length: 6, obscureText: false, obscuringCharacter: '*', keyboardType: TextInputType.number, autoDismissKeyboard: true, enableActiveFill: true, inputFormatters: [FilteringTextInputFormatter.digitsOnly], onChanged: (value) {}, textStyle: TextStyle(color: appTheme.black900, fontSize: getFontSize(24), fontFamily: 'Open Sans', fontWeight: FontWeight.w400), pinTheme: PinTheme(fieldHeight: getHorizontalSize(50), fieldWidth: getHorizontalSize(50), shape: PinCodeFieldShape.box, borderRadius: BorderRadius.circular(getHorizontalSize(12)), selectedFillColor: Color(0X1212121D), activeFillColor: Color(0X1212121D), inactiveFillColor: Color(0X1212121D), inactiveColor: appTheme.red70001, selectedColor: appTheme.red70001, activeColor: appTheme.red70001)))), Align(alignment: Alignment.centerLeft, child: Padding(padding: getPadding(top: 18), child: Text("msg_please_enter_a_valid2".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.bodyLargeRed70001))), CustomElevatedButton(text: "lbl_verify".tr, margin: getMargin(top: 42), buttonStyle: CustomButtonStyles.fillPrimary.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(double.maxFinite, getVerticalSize(54)))), buttonTextStyle: theme.textTheme.titleMedium!, onTap: () {onTapVerify();}), Padding(padding: getPadding(top: 26, bottom: 5), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_don_t_receive_a2".tr, style: theme.textTheme.bodyLarge), TextSpan(text: "lbl_resend_now".tr, style: CustomTextStyles.titleMediumBlack900SemiBold)]), textAlign: TextAlign.left))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] library to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleft2() { Get.back(); } 
/// Navigates to the resetPasswordScreen when the action is triggered.

/// When the action is triggered, this function uses the `Get` package to
/// push the named route for the resetPasswordScreen.
onTapVerify() { Get.toNamed(AppRoutes.resetPasswordScreen, ); } 
 }
